version: "3.9"

networks:
  tecmides-network:
    driver: bridge

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: tecmides
      POSTGRES_USER: tecmides
      POSTGRES_PASSWORD: teste321
    ports:
      - "5432:5432"
    networks:
      - tecmides-network

  tecmides-api:
    image: rodrigomsr2/tecmides-api
    command: ["/wait-for-it.sh", "postgres:5432", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"
    networks:
      - tecmides-network
    depends_on:
      - postgres
      
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    networks:
      - tecmides-network
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      
  moodle:
    image: docker.io/bitnami/moodle:3
    command: bash -c "mkdir /bitnami/moodle/report/tecmides && install_packages git && git clone https://github.com/rodrigomsr2/plugin.git /bitnami/moodle/report/tecmides"
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - tecmides-network
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
      
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local